Add AmiiboTag.FromIdentificationBlock
Falco20019/libamiibo pull request #7
Opened 2023-09-22 16:37 UTC by DanTheMan827

2023-09-26 08:38 UTC, Falco20019 requested changes
Only minor changes requested.

2023-09-26 08:38 UTC, Falco20019 commented on libamiibo/Data/AmiiboTag.cs
> +        private static readonly byte[] tagHeader = new byte[] { 0x04, 0x01, 0x02, 0x8F, 0x03, 0x04, 0x05, 0x06, 0x04, 0x48, 0x0f, 0xe0, 0xf1, 0x10, 0xff, 0xee, 0xa5, 0x00, 0x00, 0x00 };
Can you split this up with comments for better overview?

Header:
9 bytes are NTAG serial, one byte internal, 2 bytes LockBytes, 4 bytes CC, 1 byte magic, 2 bytes write count, 1 byte figure version

Footer:
4 bytes dynamic lock bytes, 4 bytes CFG0, 4 bytes CFG1

2023-09-26 08:38 UTC, Falco20019 commented on libamiibo/Data/AmiiboTag.cs
> +        private static readonly byte[] tagHeader = new byte[] { 0x04, 0x01, 0x02, 0x8F, 0x03, 0x04, 0x05, 0x06, 0x04, 0x48, 0x0f, 0xe0, 0xf1, 0x10, 0xff, 0xee, 0xa5, 0x00, 0x00, 0x00 };
Also please don't mix uppercase and lowercase hex notation. The code base uses uppercase hex.

2023-09-26 08:38 UTC, Falco20019 commented on libamiibo/Data/AmiiboTag.cs
> +            identificationBlock.CopyTo(decryptedNtag, 84);
The rest of the code uses hex for positions. Please adjust to keep it consistent.

2023-09-26 15:44 UTC, DanTheMan827 commented
I've made the requested changes.  If you want me to squash the commits, I can do that later.

I was thinking though.  Would you rather have the NTAG layout, or just generate an internal tag directly? I did the former because I already knew where everything went.

2023-09-27 09:50 UTC, Falco20019 commented
> I've made the requested changes. If you want me to squash the commits, I can do that later.
> 
> I was thinking though. Would you rather have the NTAG layout, or just generate an internal tag directly? I did the former because I already knew where everything went.

I first added a comment asking exactly that. But since the NTAG serial is really consisting of 9 and not 8 byte (wrongly mapped in the code right now due to Nintendos internal layout only using 8) I deleted it before finishing the review since it's cleaner that way :)

2023-09-27 09:51 UTC, Falco20019 approved these changes
Thanks for your contribution!

2023-09-27 09:52 UTC, merged

2023-09-27 13:16 UTC, Falco20019 commented on libamiibo/Data/AmiiboTag.cs
> +        private static readonly byte[] tagFooter = new byte[] {
It was after the merge that I remembered that this is exactly `NtagHelpers.CONFIG_BYTES`.